#a container can be generated out of a typical system description:
{pkgs, ip, name, ...}:
# ip is the ip for the container that will be automatically generated by nixcloud-container
# name is the name of the container
{
  services.openssh.enable = true;
  services.openssh.ports = [ 22 ];
  environment.systemPackages = [ pkgs.dfc pkgs.vim pkgs.dfc];
}
